### ISSUE TITLE
server blocks and opentracing_propagate_context

### ISSUE THREAD

**Issue by ppmspetrovic** [instana/nginx-tracing#35]
This FAQ was very helpful: https://github.com/instana/nginx-tracing#directive-proxy_set_header-only-in-server-blocks

Is it true that `opentracing_propagate_context` must be set again _after_ all `proxy_set_header` statements in the `server` block have been stated?  If this is true, it might be helpful to state this explicitly.

Also, for those of us who may not be nginx experts, some explanation of why `opentracing_propagate_context` must be re-stated in these cases would be very helpful.

Thank you.

**Comment by sriemer** [comment]
Hi Mark (@ppmspetrovic),

thanks for your message.
Part of the explanation is in https://github.com/instana/nginx-tracing#edit-the-nginx-configurations.
It is shown for location blocks there.

Yes, `opentracing_propagate_context` has to be set for every block where `proxy_set_header` is found.
The reason is that `opentracing_propagate_context` is based on `proxy_set_header` internally. There is no way to set that automatically from the `nginx-opentracing` module code due to the way how NGINX configuration structures work.

Patching the NGINX configuration automatically by the [Instana AutoTrace WebHook](https://github.com/instana/instana-autotrace-webhook) in Kubernetes environments is our goal for the future.

I'll amend the documentation accordingly. Thanks for the pointer.

**Comment by sriemer** [comment]
Hi Mark (@ppmspetrovic),
can you please review PR #39? TIA
